[tool.poetry]
name = "better-proxy"
version = "1.0.0"
description = "Better proxy!"
authors = ["Alen <alen.kimov@gmail.com>"]
readme = "README.md"
packages = [{include = "better_proxy"}]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
